source 'https://rubygems.org'

gem 'rails', '2.3.5'
gem 'rdoc'
gem 'mysql'
gem 'warden', '0.10.7'
gem 'devise', '1.0.11'
gem 'will_paginate', '~> 2.0'
gem 'settingslogic'                                                             
gem 'fastercsv'                                                                 
#gem 'rest-client'                                                                
gem 'nokogiri', '1.5.0'
gem 'mechanize', '2.7.0'                                                                 
gem 'json', '1.5.0'
gem 'rake',  '0.8.7'
gem 'bundler'
gem 'activerecord-mysql2-adapter'
gem 'passenger'
gem 'rcov', '1.0.0'
gem 'colorize'
gem 'actionmailer', '2.3.5'
